### ISSUE TITLE
Grunt

### ISSUE THREAD

**Issue by darol100** [darol100/lazydubuntu#2]
## Problem:
We need to provide Grunt in this project.
## Solution:
Download, Install and configure grunt.

http://gruntjs.com/

**Comment by horvan** [comment]
[see] (https://github.com/darol100/lazydubuntu/issues/5#issuecomment-71383719)

**Comment by darol100** [comment]
This issue was fix on a6f8ac7a75410d073849ce859246a6e49289d122
