### ISSUE TITLE
Software spec please

### ISSUE THREAD

**Issue by HenryOrrin** [darol100/lazydubuntu#24]
@darol100 Please write out minimum the specs for this project, so I can get working on this asap. This is not a contract for development, just so I can have a starting point. Or rather, we can also do this on trello.

**Comment by darol100** [comment]
## Recommended Requirements
- Quad Core ΜHz processor 
- 40 GB of hard-drive space 
- 4096 MiB RAM
- 3D Acceleration Capable Videocard with at least 256 MB 
- Internet connection


## Minimal Requirements
- Dual Core Core processor 
- Internet connection
- 1024 MiB RAM 
- 10 GB of hard-drive space 
- VGA capable of 1024x768 screen resolution
