### ISSUE TITLE
Compass

### ISSUE THREAD

**Issue by darol100** [darol100/lazydubuntu#5]
## Problem:
We need to provide Compass in this project.
## Solution:
Download, Install and configure Compass.

http://compass-style.org/

**Comment by horvan** [comment]
```Shell
apt -qq -y install  software-properties-common >> /dev/null 2>&1

updatenodejs(){

sudo apt-add-repository -y ppa:chris-lea/node.js >>/dev/null 2>&1
sudo apt-get install nodejs
#installs preproceccor languages and grunt
getgems(){
updatenodejs  >> /dev/null 2>&1
gem install sass  >> /dev/null 2>&1
gem install compass  >> /dev/null 2>&1
npm install -g grunt-cli >> /dev/null 2>&1
getdrush >> /dev/null 2>&1
}
'''

Resourcees:
https://github.com/drubuntu/installation/blob/master/functions.sh
https://www.deeson.co.uk/labs/using-grunt-bootstrap-compass-and-sass-drupal-sub-theme

**Comment by horvan** [comment]
[see #5 Compass] (https://github.com/darol100/lazydubuntu/issues/5#issuecomment-71383719)

**Comment by darol100** [comment]
I have run every command manually to see if the installation is successful and I run to this error when I was installing SASS.

![screenshot from 2015-01-26 07 47 10](https://cloud.githubusercontent.com/assets/6808460/5907307/d8540e6e-a552-11e4-8e65-984a56616df0.png)

So I installed ruby before the sass.

```bash
#Install Ruby
sudo apt-get install ruby
# Then I installed SASS
gem install sass 
sass -v # To verify if sass is installed properly.
```

I ran into a problem when I try to install compass.

![screenshot from 2015-01-26 07 54 56](https://cloud.githubusercontent.com/assets/6808460/5907338/1b8fa972-a553-11e4-9393-4a2ff9d5fda0.png)

This can was solve by updating the packages.

```bash
gem update --system
gem install compass
```
