### ISSUE TITLE
Validation Scripts

### ISSUE THREAD

**Issue by darol100** [darol100/lazydubuntu#6]
### Problem:
Installation problems with composer and other packages.

### Solution
We need to created a script that will validate some of the packages install.

**Comment by horvan** [comment]
What is your probleem here? maybe we can help out

**Comment by darol100** [comment]
@horvan thank you to jumping it. The reason I open this issue was because someone was complaining the Drush was not installed properly. 

So, during the installation process we would like to used some of the new packages that have been install. If there is an error we would know that is not been installed properly. I do not know if that makes sense.

**Comment by darol100** [comment]
## Recommended Requirements
- Quad Core ΜHz processor 
- 40 GB of hard-drive space 
- 4096 MiB RAM
- 3D Acceleration Capable Videocard with at least 256 MB 
- Internet connection


## Minimal Requirements
- Dual Core Core processor 
- Internet connection
- 1024 MiB RAM 
- 10 GB of hard-drive space 
- VGA capable of 1024x768 screen resolution

**Comment by horvan** [comment]
In general this make sense for me. What you can do is. 

1. Grab the installation instructions from github and write it in a script. 

2. Create a symbolic link with ln -s 

3. Check if the symbolic link works probably

By running the drush command and redirecting the output in a file and check if the first line from the drush help text is in the file you can check if the installation has worked well. 

I'll write the code and than re answere to this.

Date: Fri, 16 Jan 2015 13:22:58 -0800

**Comment by horvan** [comment]
If you like to make absolutely  sure to install the latest version form GitHub for the current user use this:

```Shell
#!/bin/bash
#before you are able to install composer php has to be installed so place this code after your lamp installation

# file has to be run with sudo

#functions to install composer and it's dependencies globaly.

getcomposer(){
# installing prerequirements
apt-get -y -qq install git git-core curl

# Composer Global installation
curl -sS https://getcomposer.org/installer | php >  /dev/null 2>&1
mv composer.phar /usr/local/bin/composer >  /dev/null 2>&1
sed -i '1i export PATH="~/.composer/vendor/bin:$PATH"' ~/.bashrc >  /dev/null 2>&1
source "$HOME"/.bashrc
}

#get drush via composer
getdrush(){
composer global require drush/drush:dev-master

#create symlink to make drush work when entering drush in terminal
if [ -f /usr/bin/drush ]; then
rm "/usr/bin/drush";
cd ~/.composer/vendor/drush/drush
ln -s  $PWD/drush /usr/bin/drush
else
cd ~/.composer/vendor/drush/drush
ln -s  $PWD/drush /usr/bin/drush

fi
}

#execute functions from above

getcomposer
getdrush
```




The result that is expected is

$ Drush Version   :  7.0-dev

If you like to speed up development just get in touch with me I have a similar project that's mor fare advanced than yours here on GitHub perhaps we should share some Ideas and code.

**Comment by darol100** [comment]
We already have Drush working (I forgot to mention). For this reason I'm going to close this issue.
